export const SHOW_TRANSACTION_LIST = '[SHOW_TRANSACTION_LIST]'
export const HIDE_TRANSACTION_LIST = '[HIDE_TRANSACTION_LIST]'
export const SHOW_SEND = '[SHOW_SEND]'
export const HIDE_SEND = '[HIDE_SEND]'
export const SHOW_RECEIVE = '[SHOW_RECEIVE]'
export const HIDE_RECEIVE = '[HIDE_RECEIVE]'
export const DISABLED_SEND_INPUT = '[DISABLED_SEND_INPUT]'
export const UN_DISABLED_SEND_INPUT = '[UN_DISABLED_SEND_INPUT]'
export const SEND_TRANSACTION = '[SEND_TRANSACTION]'
export const SEND_TRANSACTION_SUCCESS = '[SEND_TRANSACTION_SUCCESS]'
export const SEND_TRANSACTION_ERROR = '[SEND_TRANSACTION_ERROR]'

export const CLOSE_SEND_TRANSACTION_SUCCESS_INFO_MODAL = '[CLOSE_SEND_TRANSACTION_SUCCESS_INFO_MODAL]'
export const CLOSE_SEND_TRANSACTION_ERROR_INFO_MODAL = '[CLOSE_SEND_TRANSACTION_ERROR_INFO_MODAL]'

export const OPEN_GENERATE_QR_CODE_MODAL = '[OPEN_GENERATE_QR_CODE_MODAL]'
export const CLOSE_GENERATE_QR_CODE_MODAL = '[CLOSE_GENERATE_QR_CODE_MODAL]'

