export const SET_DEFAULT_WALLETS_VIEW = '[SET_DEFAULT_WALLETS_VIEW]'


// new steps to generate wallet
export const GENERATE_WALLET_NEW = '[GENERATE_WALLET_NEW]'
export const SELECTE_BLOKCHAIN_NEW = '[SELECTE_BLOKCHAIN_NEW]'
export const COIN_CHEKED_NEW = '[COIN_CHEKED_NEW]'
export const GO_TO_GENERATE_SEED_STEP_NEW = '[GO_TO_GENERATE_SEED_STEP_NEW]'
export const GENERATE_SEED_NEW = '[GENERATE_SEED_NEW]'
export const SET_SEED_NEW = '[SET_SEED_NEW]'
export const GENERATE_PRIVATE_KEY_NEW = '[GENERATE_PRIVATE_KEY_NEW]'
export const GO_TO_WALLET_INFO_STEP_NEW = '[GO_TO_WALLET_INFO_STEP_NEW]'
export const GENERATE_WALLET_COMPLETED_NEW = '[GENERATE_WALLET_COMPLETED_NEW]'
export const ADD_WALLET_TO_WALLETS_NEW = '[ADD_WALLET_TO_WALLETS_NEW]'
export const GENERATE_WALLET_CANCEL_NEW = '[GENERATE_WALLET_CANCEL_NEW]'
export const UPLOAD_WALLETS_NEW = '[UPLOAD_WALLETS_NEW]'
export const UPLOAD_UNIQUE_WALLETS_NEW = '[UPLOAD_UNIQUE_WALLETS_NEW]'
export const UPLOAD_AND_REPLACE_DUPLICATE_WALLETS_NEW = '[UPLOAD_AND_REPLACE_DUPLICATE_WALLETS_NEW]'
export const ADD_NEW_COINS_NEW = '[ADD_NEW_COINS_NEW]'
export const SHOW_COIN_DETAILS_NEW = '[SHOW_COIN_DETAILS_NEW]'
export const GET_TRANSACTIONS_BY_SELECTED_COIN_NEW = '[GET_TRANSACTIONS_BY_SELECTED_COIN_NEW]'
export const GET_LINE_CHART_DATA = '[GET_LINE_CHART_DATA]'
export const GET_LINE_CHART_DATA_SUCCESS = '[GET_LINE_CHART_DATA_SUCCESS]'
export const GET_LINE_CHART_DATA_ERROR = '[GET_LINE_CHART_DATA_ERROR]'
export const CLOSE_WALLETS_UPLOAD_WARNING_MODAL = '[CLOSE_WALLETS_UPLOAD_WARNING_MODAL]'
export const CHECK_COINS_BALANCE = '[CHECK_COINS_BALANCE]'
export const UPDATE_COINS = '[UPDATE_COINS]'
export const UPDATE_SELECTED_COINS = '[UPDATE_SELECTED_COINS]'
export const UPDATE_COINS_COURSES = '[UPDATE_COINS_COURSES]'

/**
 * ===================== Add new coins =====================
 */
export const ADD_NEW_COINS = '[ADD_NEW_COINS]'
export const SHOW_COIN_DETAILS = '[SHOW_COIN_DETAILS]'
export const SHOW_COIN_DETAILS_SUCCESS = '[SHOW_COIN_DETAILS_SUCCESS]'
/**
 * =========================================================
 */


/**
* ===================== Show/Hide CoinSelector and CoinDetails on mobile ==================
*/
export const OPEN_COIN_SELECTOR_ON_MOBILE = '[OPEN_COIN_SELECTOR_ON_MOBILE]'
export const CLOSE_COIN_SELECTOR_ON_MOBILE = '[CLOSE_COIN_SELECTOR_ON_MOBILE]'
export const SHOW_SPINNER = '[SHOW_SPINNER]'
export const HIDDEN_SPINNER = '[HIDDEN_SPINNER]'
export const SHOW_COIN_COURSE = '[SHOW_COIN_COURSE]'

export const OPEN_DEFAULT_VIEW_WALLETS_MODAL = '[OPEN_DEFAULT_VIEW_WALLETS_MODAL]'
export const CLOSE_DEFAULT_VIEW_WALLETS_MODAL = '[CLOSE_DEFAULT_VIEW_WALLETS_MODAL]'
